<?php


namespace app\components;


use yii\base\Widget;

class MenuWidget extends Widget
{
    /**
     * @var $tpl
     * Чтобы виждет стал более универсальным и смог работать более чем с одним шаблоном
     */
    public $tpl;
    /**
     * @var $ul_class
     * css класс будем присваивать для меню
     */
    public $ul_class;
    /**
     * @var $data
     * получать массив категории
     */
    public $data;
    /**
     * @var $tree
     * формируем дерево меню
     */
    public $tree;
    /**
     * @var $menuHtml
     * готовая верстка меню
     */
    public $menuHtml;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        if ($this->ul_class === null){
            $this->ul_class = 'menu';
        }

        if ($this->tpl === null){
            $this->tpl = 'menu';
        }
        $this->tpl .='.php';
    }

    public function run()
    {
        return $this->tpl;
    }

}